### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by murthychandrappa** [jorabin/KeePassJava2#12] opened 2017-05-24 17:00 UTC
library which works fine while loading for the first time but from the subsequent calls, it take around 30-40 seconds.

I tried using all 3 loaders but everything takes a long time to load. I have records with 3000 entries. Could you please check this performance issue?

Thanks,
Murthy

**Comment by jorabin** [comment] 2017-05-25 10:11
Can you try running OpenDbExample in the module examples? Also can you provide a link to your code?

thanks

**Comment by murthychandrappa** [comment] 2017-05-26 15:12
I executed OpenDbExample, both Simple & jaxb works fine locally but Dom loader was taking forever time.
But when i used either simple or jaxb loader and deploy in Cloud Foundry, it works only for first load and take 30sec to 5min to load for subsequent calls. You could try pushing your code into cloud foundry here https://pivotal.io/platform

you could create a trial account and try.

**Comment by vboulaye** [comment] 2017-07-02 06:36
I had a similar problem on my laptop, and it turns out being related to `/dev/random` blocking, so getting a new random seed would take forever. It impacted other programs as well (randomly!).  

On the pivotal website there is an explanation on how to switch to `dev/urandom` (this should not block): 
https://discuss.pivotal.io/hc/en-us/articles/230141007-Java-Web-Applications-Slow-Startup-or-Failing

**Comment by jorabin** [comment] 2017-07-06 10:33
That's certainly interesting - thanks for pointing out.

@murthychandrappa can you confirm that this helps with your problem?

**Comment by jorabin** [comment] 2018-01-20 17:02
leaving this open for now Oracle provides a way of testing if you have this problem: https://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html

**Comment by MadMaxLab** [comment] 2021-04-14 09:53
Hi!

It seems that this performance issue actual in 2021. 
This is my test on the default JVM setting in Linux:
![Screenshot from 2021-04-14 12-32-25](https://user-images.githubusercontent.com/51915357/114689674-9dfb3d80-9d1e-11eb-92b0-5ea3e522dcb9.png)

This is normal behavior:
![Screenshot from 2021-04-14 12-09-33](https://user-images.githubusercontent.com/51915357/114689666-9b004d00-9d1e-11eb-8f75-6355c6c44bfe.png)

The instruction from Oracle that was linked before is out of date for JDK 11 and later. You should correct the settings file in your $/usr/lib/jam/<version of jdk>/conf/security/java.security file.

According to this 12 years old issue [()](https://stackoverflow.com/questions/137212/how-to-deal-with-a-slow-securerandom-generator) to avoid config setting in Linux we can refactor code from 
```
   public KdbxHeader() {
        **SecureRandom random = new SecureRandom();**
        cipherUuid = AES_CIPHER;
        compressionFlags = CompressionFlags.GZIP;
        masterSeed = random.generateSeed(32);
        transformSeed = random.generateSeed(32);
        transformRounds = 6000;
        encryptionIv = random.generateSeed(16);
        protectedStreamKey = random.generateSeed(32);
        streamStartBytes = new byte[32];
        protectedStreamAlgorithm = ProtectedStreamAlgorithm.SALSA_20;
    }
```

To: 
```
   public KdbxHeader() {
        **SecureRandom random = SecureRandom.getInstance("SHA1PRNG");**
        cipherUuid = AES_CIPHER;
        compressionFlags = CompressionFlags.GZIP;
        masterSeed = random.generateSeed(32);
        transformSeed = random.generateSeed(32);
        transformRounds = 6000;
        encryptionIv = random.generateSeed(16);
        protectedStreamKey = random.generateSeed(32);
        streamStartBytes = new byte[32];
        protectedStreamAlgorithm = ProtectedStreamAlgorithm.SALSA_20;
    }
```

I think I could test it and make a PR with a fix if you don't undermind.

**Comment by jorabin** [comment] 2023-08-22 11:27
Fixed in 2.2.1

**Comment by lordgreg** [comment] 2024-09-18 08:22
Hi. Sorry for bumping the closed issue but, this is still unresolved for us. For each next call of the tool, it takes longer to execute. I've used KeePassJava2 2.1.4 and then 2.2.1 and was still able to reproduce the error.

Anything else that I am missing?

Using Java17 to compile and start the lib.

**Comment by jorabin** [comment] 2024-09-18 09:32
Hi

Which OS are you using?

Did you try the [test from Oracle](https://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html)?

Have you tried using a different SecureRandom algorithm?

Thanks

**Comment by lordgreg** [comment] 2024-09-18 11:25
Hi Jorabin and thank you for commenting,... I will try everthing you've suggested soon and give you a feedback asap.

**Comment by lordgreg** [comment] 2024-09-23 06:21
Hi @jorabin,

I've checked the Oracle test and I am not affected by "waiting time", nevertheless, I've also tested execution of JAR with `-Djava.security.egd=file:/dev/./urandom` parameter. It didn't changed time execution.

OS: Windows 10, Java 17 on **WSL2, Unbutu**:
```
java -version
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 17.0.12+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)
```

I am using `DomDatabaseWrapper.load` to load the kdbx Files.

Also, our KDBX Files are not small, but not that huge either. Each KDBX has 6 Groups, each having 25 Entries. About half entries have more "String Fields".

And, I haven't used different `SecureRandom` algorithm.

Also, this Problem occurs when opening different KDBX Files one after another and not when reopening already opened KDBX. So the use-case to reproduce is:
- open kdbx1, takes 10 seconds
- open kdbx2, takes 20 seconds
- open kdbx3, takes 30 seconds

**Comment by jorabin** [comment] 2024-09-23 09:21
Please try moving to 2.2.2 and use the Jackson implementation.

**Comment by jorabin** [comment] 2024-09-23 12:40
Also, it would be interesting to know what happens when you run OpenDbExample https://github.com/jorabin/KeePassJava2/blob/2c47bd7f1513353f1594b95534a91d24a3078088/example/src/main/java/org/linguafranca/pwdb/kdbx/OpenDbExample.java#L72

**Comment by lordgreg** [comment] 2024-10-02 06:09
Hi @jorabin, I've upgraded to 2.2.2 and switched to JaxbDatabase. All databases are opening under 5 seconds, no matter the size or how many times I execute the commands. I think the issue can now be closed. Also, I am not sure how many people have several KDBX Files to get the exact use-case out of it, but, it would be maybe wise to update the readme that the DomWrapper has been showing some Performance issues. 


Thank you for your support!

**Comment by jorabin** [comment] 2024-10-04 11:00
Hi @lordgreg 

Thanks for the update.

There are significant warnings in the README that the DomWrapper is slow ...

> A DOM based implementation of KDBX. Being DOM based it is rather slow, but messes less with existing content than the other implementations. Known to work on Android.

Suggest that you use Jackson, not Jaxb, as 2.2.3 supports improved management of secrets in memory for Jackson only and I will drop support for Jaxb (as well as Dom and Simple) altogether in version 3.

Would be good to hear how that goes for you and will close this issue (again) having heard back.

thanks

**Comment by lordgreg** [comment] 2024-10-04 11:02
> Would be good to hear how that goes for you and will close this issue (again) having heard back.

Give me until Monday, I will provide the feedback :)

Kind regards.

**Comment by lordgreg** [comment] 2024-10-07 08:01
Hi @jorabin - I've switched to JacksonDatabase and currently see no time difference, everything works exceptional as it should. No hiccups even after opening the 4th, 5th or 6th Database. From my point of view, the issue can be closed.

Thank you for your awesome support and work!

**Closed** 2024-10-07 09:25 UTC
Labels: enhancement, Version 2.2
