### ISSUE TITLE
Split Packages and JPMS

### ISSUE THREAD

**Issue by AugustNagro** [jorabin/KeePassJava2#16] opened 2018-01-18 23:34 UTC
Because KeePassJava2 has split packages (org.linguafranca.pwdb.kdbx in both KeePassJava2.kdbx and KeePassJava2.simple), the library can't be used with the Java 9 module system.

Would there be any interest in refactoring? For reference: https://stackoverflow.com/a/42358212

Regards,

August

**Comment by jorabin** [comment] 2018-01-20 13:59
Thanks for the heads up, that is definitely non intentional.

**Comment by AugustNagro** [comment] 2018-01-21 05:12
Thanks for the quick response!

I also filed an issue for SimpleFramework: https://github.com/ngallagher/simpleframework/issues/24

**Comment by jorabin** [comment] 2018-01-21 14:24
Here's where we are on this (2018-01-21): 

I pushed a fix for this to Master, but it started failing Travis. Turns out that was because Travis doesn't support the oracle jdk7 any more. I tried switching to openjdk7 and also oraclejdk8 - but both cause an intermittent unit test failure, I think caused by XmlOutputStreamFilter in the simple module.

So the code in master solves the package problem, but depending on the java runtime may be unreliable in execution. 

There are some possible fixes. One is to rewrite the offending code, but the existing code is a bit of a hack workaround for the existence of inner stream encrypted base64 encoded fields, which it did not seem there is an easy way of converting using simple. Will revisit use of PipedOutputStream for this.

Another way might be to fork and add relevant functionality to simple. Which I'd prefer not to do.

There may be other fixes. Meanwhile, @AugustNagro - can you confirm that the change to package structure actually fixes the issue you report here?

Many thanks

**Comment by AugustNagro** [comment] 2018-01-21 21:32
Working well, thanks!

Would it be possible to add Automatic Module names as well? For example:

      <manifestEntries>
        <Automatic-Module-Name>org.linguafranca.pwdb.KeePassJava2.dom</Automatic-Module-Name>
      </manifestEntries>

**Comment by jorabin** [comment] 2018-01-22 10:58
Yes, happy to do that, would you like to create a pull request against branch `develop` for that?

Many thanks!

**Comment by jorabin** [comment] 2018-01-23 00:51
Closing as reported that it works now ...

**Closed by jorabin** 2018-01-23 00:51 UTC
